import React from "react";
import {
  MagnifyingGlassWhite,
  ArrowRight,
  Heart,
  BlackUsers,
} from "../../../assets/svgs/index";
import { StrategyFtn } from "../../../Store/StrategySlice/StrategySlice";
import { useDispatch } from "react-redux";
// ///////////////////////   *****************   ///////////////////////
// ///////////////////////   *****************   ///////////////////////
const ProvidersTOS = () => {
  const dispatch = useDispatch();

  return (
    <div>
      <div className="bg_white rounded-[12px] p-5 ">
        <h1 className="black text-[20px] font-[700]">
          Please Review Our Provider Terms
        </h1>
        <div className="mt-5">
          {/* 1 */}
          <div className="flex gap-3 mt-3">
            <div className="">
              <h1 className="text-[16px] font-semibold bg-[#CAFD5D] rounded-full py-[4px] px-[12px] flex justify-center">
                1
              </h1>
            </div>

            <div className="my-auto">
              <h4 className="text-[14px] font-[700] black">
                Eligibility & Compliance
              </h4>
              <p className="text-[16px] gray mt-1 leading-5">
                You confirm that you are legally permitted to provide trading
                strategies in your jurisdiction. You will not share strategies
                that violate laws or platform rules (e.g., market manipulation).
              </p>
            </div>
          </div>
          {/* 2 */}
          <div className="flex gap-3 mt-3 mt-3">
            <div className="">
              <h1 className="text-[16px] font-semibold bg-[#CAFD5D] rounded-full py-[4px] px-[12px] flex justify-center">
                2
              </h1>
            </div>

            <div className="my-auto">
              <h4 className="text-[14px] font-[700] black">Risk Disclosure</h4>
              <p className="text-[16px] gray mt-1 leading-5">
                Trading involves substantial risk, and past performance does not
                guarantee future results. Subscribers assume full responsibility
                for using your strategies.
              </p>
            </div>
          </div>
          {/* 3 */}
          <div className="flex gap-3 mt-3">
            <div className="">
              <h1 className="text-[16px] font-semibold bg-[#CAFD5D] rounded-full py-[4px] px-[12px] flex justify-center">
                3
              </h1>
            </div>
            <div className="my-auto">
              <h4 className="text-[14px] font-[700] black">Revenue & Fees</h4>
              <p className="text-[16px] gray mt-1 leading-5">
                The platform retains a [X]% fee on all subscription revenue
                generated by your strategies. Payouts occur monthly, subject to
                minimum thresholds and anti-fraud checks.
              </p>
            </div>
          </div>
          {/* 4 */}
          <div className="flex gap-3 mt-3">
            <div className="">
              <h1 className="text-[16px] font-semibold bg-[#CAFD5D] rounded-full py-[4px] px-[12px] flex justify-center">
                4
              </h1>
            </div>
            <div className="my-auto ">
              <h4 className="text-[14px] font-[700] black">
                Provider Obligations
              </h4>
              <ul className="text-[16px] gray mt-1 leading-7 list-disc pl-5">
                <li className="">
                  Disclose any conflicts of interest (e.g., trading positions
                  linked to your strategies).
                </li>
                <li className="">
                  Avoid spam, misleading claims, or impersonation of other
                  traders.
                </li>
                <li className="">
                  Update strategies promptly if market conditions change
                  materially.{" "}
                </li>
                <li className="">
                  Notify the platform of any legal/regulatory actions affecting
                  your eligibility.
                </li>
              </ul>
            </div>
          </div>
          <label className="flex items-center gap-2 cursor-pointer mt-5">
            <input type="checkbox" className="peer hidden" id="customCheck" />
            <div className="w-[24px] h-[24px] rounded-[8px] bg-white border border-[#CAFD5D] peer-checked:bg-[#CAFD5D] flex items-center justify-center transition-colors">
              <svg
                className="hidden peer-checked:block w-[14px] h-[14px] text-black"
                fill="none"
                stroke="currentColor"
                strokeWidth="3"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <p className="black font-[700] text-[14px]">
              I have read and agree to the provider agreement
            </p>
          </label>
        </div>
        <hr className="mt-4" style={{ color: "#E8E8E8" }} />
        <div className="mt-5 flex justify-between gap-4">
          <div className="my-auto">
            <h1 className="cursor-pointer border border-[1.5px] border-[#E8E8E8] rounded-[8px] px-[15px] py-[7px] flex gap-2">
              Cancel
            </h1>
          </div>
          <div className="my-auto">
            <button
              onClick={() => dispatch(StrategyFtn("Step1"))}
              className="black cursor-pointer bg_primaryGreen rounded-[8px] font-[500] px-[20px] py-[7px] flex gap-2"
            >
              Start Strategy Creation{" "}
              <img src={ArrowRight} alt="ArrowRight" className="" />{" "}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProvidersTOS;
